//IMPORTAMOS DE LA SIGUIENTE MANERA NUESTRO SERVER
const Server = require("./models/server");

//DE ESTA MANERA PODEMOS LLAMAR A TODAS NUESTRAS VARIABLES DE ENTORNO PARA UTILIZARLAS
require('dotenv').config();


//ATRAPAMOS EL SERVIDOR EN UNA CONSTANTE PARA PODER ACCEDER A TODAS SUS FUNCIONES
const server = new Server();

//LLAMAMOS LA FUNCION QUE EJECUTA NUESTRO SERVIDOR
server.execute();






